//
// Created by dor on 24/05/2020.
//
#include"doctest.h"
#include <iostream>
#include "DemoGame.hpp"

TEST_CASE("testZero"){
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
};
TEST_CASE("testOne") {
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
            CHECK(1==1);
};
TEST_CASE("testTwo") {
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
            CHECK(2==2);
};
TEST_CASE("testThree") {
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
            CHECK(3==3);
};
TEST_CASE("testFour") {
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
            CHECK(4==4);
};
TEST_CASE("testFive") {
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
            CHECK(5==5);
};